language: php
sudo: false
branches:
  except:
    - experimental
cache:
  directories:
    - $HOME/.composer/cache/files
matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
  allow_failures:
    - php: 7.2
    - php: 7.3
    - php: nightly
  fast_finish: true
before_install:
  - composer selfupdate
install:
  - composer update --no-interaction
script:
  - ./vendor/bin/phpunit.phar --coverage-clover build/logs/clover.xml
after_success:
  - ./vendor/bin/test-reporter
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f5bcd59af82eb6dd98b3
    on_success: always
    on_failure: always
    on_start: never
addons:
  code_climate:
    repo_token: 7f44085be777d3dec1dd765e61461ad1a6f62110e8607f50c25214a417f2af1a
